version: "3.5"

networks:
  localhost:
    name: svirgil_network
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/svirgil/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/svirgil/data/mariadb
      o: bind
      type: none

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx_container
    image: nginx_image
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wp_container
    build: ./wordpress
    volumes:
      - wordpress:/var/www/wordpress
    image: wordpress_image
    networks:
      - localhost
    restart: always
  mariadb:
    container_name: mariadb_container
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    image: mariadb_image
    networks:
      - localhost
    restart: always