version: "3.5"

networks:
  localhost:
    name: network
#==== VOLUMES ===================================================================#
volumes:
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /home/svirgil/data/wordpress
      o: bind
      type: none
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /home/svirgil/data/mariadb
      o: bind
      type: none
#==== SERVICES ===================================================================#
services:
#==== NGINX ===================================================================#
  nginx:
    depends_on:
      - wordpress
    container_name: nginx_container
    image: nginx_image
    env_file: .env
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - localhost
    restart: always
#==== WORDPRESS ===================================================================#
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_container
    build: ./wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    image: wordpress_image
    env_file: .env
    networks:
      - localhost
    restart: always
  #==== MARIADB ===================================================================#
  mariadb:
    container_name: mariadb_container
    build: ./mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    image: mariadb_image
    env_file: .env
    networks:
      - localhost
    restart: always
